# lastlayer project
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.agbuxkqjovpanhrgdcsp
spring.datasource.password=F*psf$+2MG_R3K&
lastlayer.jwt-secret=YjM0ZDEyN2E5YjU4ZjNlNmEyYjVjOGQxZTRmN2EwYjNjNmQ5ZTJmNWE4YjFjNGQ3ZTBmM2E2YjljMmQ1ZThm